version: '3.7'

services:

  mongodb:
    image: mongo
    ports:
      - 27017:27017

  cataloger_backend:
    container_name: cataloger_backend
    build: .
    expose:
      - "3000"
    ports:
      - 3000:3000
    depends_on:
      - mongodb